# Generated by Django 6.0.2 on 2026-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
