# Generated by Django 6.0.2 on 2026-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('kz', 'kz')], default='en', help_text='User language', max_length=10, verbose_name='Preferred languages'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
